### ISSUE TITLE
The extension isn't opening and is only loading in vscode. 

### ISSUE THREAD

**Issue by AviralCoder** [sherwyn11/Todos-VSCode-Extension#1]
Extension was not loading. It added another item in the left bar but then it wasn't loading.

**Comment by sherwyn11** [comment]
There may be a case that the extension does not load on first time usage. If this problem occurs, go to the Command Palette of VS Code using ```⌘ + ⇧ + P```  or ```Ctrl + Shift + P``` and select the option Todos-VSCode: Refresh. I'm still trying to figure this issue out. If you do have any suggestions do let me know.

**Comment by AviralCoder** [comment]
Okay now it is working.... it is a really usefull extension, just one thing, i use dark theme and the input color is black, so can you make it so that i detects the theme and then makes the color of the input either white or black.

Also I recommend styling the buttons.
Rest all is fine. Maybe it takes time to load.

**Comment by sherwyn11** [comment]
Thank you for your suggestions! Will work on them in the future. I had styled the buttons initially, but vscode gets regular updates so sometimes that messes up the styling. Will fix that soon. Thank you for giving the extension a try! Please leave a :star: on my repo if you found it useful! Also please do give it a rating in the vscode marketplace, if you feel like. Thank you! :octocat:

**Comment by AviralCoder** [comment]
alright
